feat: header 작업
Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-FE pull request #110
Opened 2023-11-09 15:38 UTC by euan-lee

## 구현 내용

## 참고 사항
스크린샷은 스토리북에 있어서 스킵했습니다.
## 궁금한 점
 헤더를 픽스를 해야되는지 sticky를 써야하는지 궁금합니다

## 이슈 번호 #105 

- close #105

2023-11-09 19:39 UTC, Lim-JiSeon reviewed
혹시 action 상에서는 husky 가 보이긴 하는데 범진님 vscode 상에서는 commit 하실 때 husky가 작동되지 않을까요? commit 하실 때 build가 된다면 작동이 잘되는 것 같습니다만 ㅠㅠ 혹시 안되신다면 꼭! 알려주세요!
추가로 현재 x로 되어 있어서 이 부분 수정해주세요! storybook, preview 모두 그렇습니다 ㅠㅠ 
물론 husky가 build가 되어도 깃허브에 pr 날릴 때 x가 될 수 있습니다만 혹시나 하고 문의드립니다!

2023-11-09 19:39 UTC, Lim-JiSeon commented on app/_components/Header/HeaderCustomer.tsx
> +      <div>강남역 2번출구</div>
제가 저번에 말씀드렸던 AddressButton을 이용해주세요! 그리고 address 를 state로 관리해서 값이 없을 경우에만 default로 강남역 2번 출구를 보여주시고 만약 주소 찾기를 해서 주소를 입력받았다면 입력받은 주소값이 보이도록 해주세요!

2023-11-09 19:39 UTC, Lim-JiSeon commented on app/_components/Header/HeaderCustomer.tsx
> +import pageRoute from '../../_constants/route';
develop branch pull 받아주세요! 현재 path로 수정되었습니다.

2023-11-09 19:39 UTC, Lim-JiSeon commented on app/_components/Header/HeaderCustomer.tsx
> +        <Link href={pageRoute.customer.login()}>
이 부분 todo로 또는 임의의 값으로 로그인을 했을 경우와 하지 않았을 경우에 로그인 버튼 분기처리해주세요.
로그인을 이미 했다면 로그인 버튼이 보이지 않도록 설정해주시면 좋을 것 같습니다~

2023-11-09 23:49 UTC, euan-lee commented on app/_components/Header/HeaderCustomer.tsx
> +        <Link href={pageRoute.customer.login()}>
네 수정하겠습니다!

2023-11-09 23:49 UTC, euan-lee commented on app/_components/Header/HeaderCustomer.tsx
> +import pageRoute from '../../_constants/route';
네 알겠습니디

2023-11-09 23:49 UTC, euan-lee commented on app/_components/Header/HeaderCustomer.tsx
> +      <div>강남역 2번출구</div>
네 확인했습니다

2023-11-09 23:50 UTC, euan-lee commented
> 혹시 action 상에서는 husky 가 보이긴 하는데 범진님 vscode 상에서는 commit 하실 때 husky가 작동되지 않을까요? commit 하실 때 build가 된다면 작동이 잘되는 것 같습니다만 ㅠㅠ 혹시 안되신다면 꼭! 알려주세요! 추가로 현재 x로 되어 있어서 이 부분 수정해주세요! storybook, preview 모두 그렇습니다 ㅠㅠ 물론 husky가 build가 되어도 깃허브에 pr 날릴 때 x가 될 수 있습니다만 혹시나 하고 문의드립니다!

컴파일 확인했는데 에러가 납니다 ㅠ 다시한번 이유 확인해 보겠습니다

2023-11-10 05:31 UTC, jgjgill commented
커밋하실 때 허스키가 동작되는지부터 공유해주시면 감사하겠습니다..!

2023-11-10 13:34 UTC, euan-lee commented
> 커밋하실 때 허스키가 동작되는지부터 공유해주시면 감사하겠습니다..!

네 동작합니다! (..ㅠ)

2023-11-10 13:42 UTC, jgjgill approved these changes

2023-11-10 13:42 UTC, jgjgill commented on app/_components/Header/assets/delightemogi.svg
`dealight-emoji`로 변경하면 좋을 것 같습니다..!

2023-11-10 13:42 UTC, jgjgill commented on app/_components/Header/HeaderCustomer.tsx
> +const CustomerHeader = () => {
파일명 `HeaderCustomer`와 컴포넌트 명이 다른 이유가 있을까요?? 🧐

2023-11-10 13:42 UTC, jgjgill commented on app/_components/Header/CustomerHeader.stories.tsx
> +  title: 'Components/CustomerHeader ',
불필요한 공백이 포함된 것 같습니다..!

```suggestion
  title: 'Components/CustomerHeader',
```

2023-11-10 13:47 UTC, jgjgill requested changes
깃허브 액션 에러 해결

2023-11-13 08:13 UTC, jgjgill approved these changes

2023-11-13 14:12 UTC, closed without merging